import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface DishData {
  name: string;
  slotCategory: string;
  kosher: boolean;
  kosherStyle: string;
  difficulty: string;
  mainProtein?: string;
  cuisine?: string;
  prepTimeMinutes?: number;
  cookTimeMinutes?: number;
  servings?: number;
  sourceUrl?: string;
  ingredients: string[];
  tags: string[];
  allergens: string[];
}

const newDishes: DishData[] = [
  // ==================== MAIN CHICKEN (25 dishes) ====================
  {
    name: 'Thai Basil Chicken',
    slotCategory: 'main_chicken',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'easy',
    mainProtein: 'chicken',
    cuisine: 'Thai',
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/257938/thai-basil-chicken-pad-krapow-gai/',
    ingredients: ['chicken breast', 'thai basil', 'garlic', 'fish sauce', 'soy sauce', 'chili', 'vegetable oil', 'sugar', 'rice'],
    tags: ['spicy', 'asian', 'quick'],
    allergens: ['gluten'],
  },
  {
    name: 'Butter Chicken',
    slotCategory: 'main_chicken',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    mainProtein: 'chicken',
    cuisine: 'Indian',
    prepTimeMinutes: 20,
    cookTimeMinutes: 40,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/246717/indian-butter-chicken/',
    ingredients: ['chicken thighs', 'butter', 'cream', 'tomato puree', 'garam masala', 'ginger', 'garlic', 'cumin', 'turmeric', 'yogurt'],
    tags: ['indian', 'creamy', 'comfort food'],
    allergens: ['dairy'],
  },
  {
    name: 'Orange Chicken',
    slotCategory: 'main_chicken',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'medium',
    mainProtein: 'chicken',
    cuisine: 'Chinese-American',
    prepTimeMinutes: 20,
    cookTimeMinutes: 25,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/75845/chinese-orange-chicken/',
    ingredients: ['chicken breast', 'orange juice', 'orange zest', 'soy sauce', 'ginger', 'garlic', 'cornstarch', 'vegetable oil', 'rice vinegar'],
    tags: ['sweet', 'asian', 'takeout'],
    allergens: ['gluten'],
  },
  {
    name: 'Chicken Korma',
    slotCategory: 'main_chicken',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    mainProtein: 'chicken',
    cuisine: 'Indian',
    prepTimeMinutes: 25,
    cookTimeMinutes: 35,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/212721/chicken-korma/',
    ingredients: ['chicken thighs', 'yogurt', 'cream', 'almonds', 'onion', 'garlic', 'ginger', 'garam masala', 'cardamom', 'cinnamon'],
    tags: ['mild', 'creamy', 'indian'],
    allergens: ['dairy', 'nuts'],
  },
  {
    name: 'Jerk Chicken',
    slotCategory: 'main_chicken',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'medium',
    mainProtein: 'chicken',
    cuisine: 'Caribbean',
    prepTimeMinutes: 30,
    cookTimeMinutes: 45,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/83473/jamaican-jerk-chicken/',
    ingredients: ['chicken pieces', 'scotch bonnet pepper', 'allspice', 'thyme', 'garlic', 'ginger', 'soy sauce', 'lime juice', 'brown sugar', 'green onion'],
    tags: ['spicy', 'grilled', 'caribbean'],
    allergens: ['gluten'],
  },
  {
    name: 'Chicken Satay',
    slotCategory: 'main_chicken',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'easy',
    mainProtein: 'chicken',
    cuisine: 'Thai',
    prepTimeMinutes: 30,
    cookTimeMinutes: 15,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/133163/chicken-satay/',
    ingredients: ['chicken breast', 'peanut butter', 'coconut milk', 'soy sauce', 'lime juice', 'curry powder', 'garlic', 'ginger', 'brown sugar'],
    tags: ['grilled', 'appetizer', 'thai'],
    allergens: ['nuts', 'gluten'],
  },
  {
    name: 'General Tso Chicken',
    slotCategory: 'main_chicken',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'medium',
    mainProtein: 'chicken',
    cuisine: 'Chinese-American',
    prepTimeMinutes: 25,
    cookTimeMinutes: 20,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/91499/general-tsos-chicken/',
    ingredients: ['chicken thighs', 'soy sauce', 'hoisin sauce', 'rice vinegar', 'dried chili', 'ginger', 'garlic', 'cornstarch', 'sesame oil'],
    tags: ['spicy', 'sweet', 'takeout'],
    allergens: ['gluten'],
  },
  {
    name: 'Lemon Pepper Chicken Wings',
    slotCategory: 'main_chicken',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'easy',
    mainProtein: 'chicken',
    cuisine: 'American',
    prepTimeMinutes: 10,
    cookTimeMinutes: 45,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/233075/lemon-pepper-chicken-wings/',
    ingredients: ['chicken wings', 'lemon zest', 'lemon juice', 'black pepper', 'garlic powder', 'butter', 'salt'],
    tags: ['wings', 'appetizer', 'crispy'],
    allergens: ['dairy'],
  },
  {
    name: 'Chicken Alfredo',
    slotCategory: 'main_chicken',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'easy',
    mainProtein: 'chicken',
    cuisine: 'Italian-American',
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/23431/chicken-alfredo/',
    ingredients: ['chicken breast', 'fettuccine', 'heavy cream', 'parmesan cheese', 'butter', 'garlic', 'parsley', 'salt', 'pepper'],
    tags: ['pasta', 'creamy', 'comfort food'],
    allergens: ['dairy', 'gluten'],
  },
  {
    name: 'Kung Pao Chicken',
    slotCategory: 'main_chicken',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'medium',
    mainProtein: 'chicken',
    cuisine: 'Chinese',
    prepTimeMinutes: 20,
    cookTimeMinutes: 15,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/176140/kung-pao-chicken/',
    ingredients: ['chicken breast', 'peanuts', 'dried chili', 'soy sauce', 'rice vinegar', 'hoisin sauce', 'garlic', 'ginger', 'green onion', 'sesame oil'],
    tags: ['spicy', 'stir-fry', 'chinese'],
    allergens: ['nuts', 'gluten'],
  },
  {
    name: 'Greek Lemon Chicken',
    slotCategory: 'main_chicken',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'easy',
    mainProtein: 'chicken',
    cuisine: 'Greek',
    prepTimeMinutes: 15,
    cookTimeMinutes: 50,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/242352/greek-lemon-chicken-and-potatoes/',
    ingredients: ['chicken pieces', 'lemon juice', 'olive oil', 'garlic', 'oregano', 'potatoes', 'chicken broth', 'salt', 'pepper'],
    tags: ['mediterranean', 'one-pan', 'roasted'],
    allergens: [],
  },
  {
    name: 'Chicken Cordon Bleu',
    slotCategory: 'main_chicken',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'hard',
    mainProtein: 'chicken',
    cuisine: 'French',
    prepTimeMinutes: 30,
    cookTimeMinutes: 35,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/8669/chicken-cordon-bleu-i/',
    ingredients: ['chicken breast', 'ham', 'swiss cheese', 'bread crumbs', 'flour', 'eggs', 'butter', 'dijon mustard'],
    tags: ['stuffed', 'fancy', 'baked'],
    allergens: ['dairy', 'gluten'],
  },
  {
    name: 'Sesame Chicken',
    slotCategory: 'main_chicken',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'medium',
    mainProtein: 'chicken',
    cuisine: 'Chinese-American',
    prepTimeMinutes: 20,
    cookTimeMinutes: 20,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/72068/sesame-chicken/',
    ingredients: ['chicken breast', 'sesame seeds', 'soy sauce', 'honey', 'garlic', 'ginger', 'cornstarch', 'vegetable oil', 'rice vinegar'],
    tags: ['sweet', 'takeout', 'asian'],
    allergens: ['gluten'],
  },
  {
    name: 'Chicken Souvlaki',
    slotCategory: 'main_chicken',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'easy',
    mainProtein: 'chicken',
    cuisine: 'Greek',
    prepTimeMinutes: 20,
    cookTimeMinutes: 15,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/172704/chicken-souvlaki/',
    ingredients: ['chicken breast', 'olive oil', 'lemon juice', 'garlic', 'oregano', 'thyme', 'pita bread', 'tzatziki', 'tomato', 'onion'],
    tags: ['grilled', 'greek', 'skewers'],
    allergens: ['dairy', 'gluten'],
  },
  {
    name: 'Honey Sesame Chicken',
    slotCategory: 'main_chicken',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'easy',
    mainProtein: 'chicken',
    cuisine: 'Asian-American',
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/228293/honey-sesame-chicken/',
    ingredients: ['chicken thighs', 'honey', 'sesame oil', 'soy sauce', 'garlic', 'ginger', 'sesame seeds', 'green onion'],
    tags: ['sweet', 'sticky', 'asian'],
    allergens: ['gluten'],
  },
  {
    name: 'Chicken Parmigiana',
    slotCategory: 'main_chicken',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    mainProtein: 'chicken',
    cuisine: 'Italian-American',
    prepTimeMinutes: 20,
    cookTimeMinutes: 30,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/223042/chicken-parmesan/',
    ingredients: ['chicken breast', 'marinara sauce', 'mozzarella cheese', 'parmesan cheese', 'bread crumbs', 'eggs', 'flour', 'basil'],
    tags: ['italian', 'baked', 'cheesy'],
    allergens: ['dairy', 'gluten', 'eggs'],
  },
  {
    name: 'Cajun Chicken Pasta',
    slotCategory: 'main_chicken',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    mainProtein: 'chicken',
    cuisine: 'Cajun',
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/8778/cajun-chicken-pasta/',
    ingredients: ['chicken breast', 'penne pasta', 'heavy cream', 'parmesan cheese', 'cajun seasoning', 'bell peppers', 'garlic', 'butter'],
    tags: ['spicy', 'pasta', 'creamy'],
    allergens: ['dairy', 'gluten'],
  },
  {
    name: 'Tandoori Chicken',
    slotCategory: 'main_chicken',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'medium',
    mainProtein: 'chicken',
    cuisine: 'Indian',
    prepTimeMinutes: 30,
    cookTimeMinutes: 35,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/142196/tandoori-chicken/',
    ingredients: ['chicken legs', 'yogurt', 'lemon juice', 'garlic', 'ginger', 'garam masala', 'cumin', 'paprika', 'turmeric', 'cayenne'],
    tags: ['grilled', 'indian', 'spiced'],
    allergens: ['dairy'],
  },
  {
    name: 'Chicken Francese',
    slotCategory: 'main_chicken',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    mainProtein: 'chicken',
    cuisine: 'Italian-American',
    prepTimeMinutes: 20,
    cookTimeMinutes: 20,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/8898/chicken-francese/',
    ingredients: ['chicken breast', 'eggs', 'flour', 'butter', 'lemon juice', 'white wine', 'chicken broth', 'parsley', 'parmesan cheese'],
    tags: ['lemon', 'pan-fried', 'elegant'],
    allergens: ['dairy', 'gluten', 'eggs'],
  },
  {
    name: 'Chicken Biryani',
    slotCategory: 'main_chicken',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'hard',
    mainProtein: 'chicken',
    cuisine: 'Indian',
    prepTimeMinutes: 45,
    cookTimeMinutes: 60,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/144553/chicken-biryani/',
    ingredients: ['chicken pieces', 'basmati rice', 'yogurt', 'onion', 'ginger', 'garlic', 'garam masala', 'saffron', 'mint', 'cilantro', 'ghee'],
    tags: ['rice', 'layered', 'festive'],
    allergens: ['dairy'],
  },
  {
    name: 'Buffalo Chicken Dip',
    slotCategory: 'main_chicken',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'easy',
    mainProtein: 'chicken',
    cuisine: 'American',
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 8,
    sourceUrl: 'https://www.allrecipes.com/recipe/68461/buffalo-chicken-dip/',
    ingredients: ['chicken breast', 'cream cheese', 'ranch dressing', 'hot sauce', 'cheddar cheese', 'blue cheese'],
    tags: ['appetizer', 'party', 'spicy'],
    allergens: ['dairy'],
  },
  {
    name: 'Chicken Milanese',
    slotCategory: 'main_chicken',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'easy',
    mainProtein: 'chicken',
    cuisine: 'Italian',
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/233500/chicken-milanese/',
    ingredients: ['chicken breast', 'bread crumbs', 'parmesan cheese', 'eggs', 'flour', 'olive oil', 'lemon', 'arugula'],
    tags: ['crispy', 'italian', 'quick'],
    allergens: ['dairy', 'gluten', 'eggs'],
  },
  {
    name: 'Mango Chicken',
    slotCategory: 'main_chicken',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'easy',
    mainProtein: 'chicken',
    cuisine: 'Caribbean',
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/228313/mango-chicken/',
    ingredients: ['chicken breast', 'mango', 'lime juice', 'honey', 'garlic', 'ginger', 'cilantro', 'red pepper flakes'],
    tags: ['fruity', 'tropical', 'sweet'],
    allergens: [],
  },
  {
    name: 'Chicken Florentine',
    slotCategory: 'main_chicken',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    mainProtein: 'chicken',
    cuisine: 'Italian',
    prepTimeMinutes: 20,
    cookTimeMinutes: 30,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/246954/easy-chicken-florentine/',
    ingredients: ['chicken breast', 'spinach', 'sun-dried tomatoes', 'cream', 'parmesan cheese', 'garlic', 'white wine', 'butter'],
    tags: ['creamy', 'spinach', 'elegant'],
    allergens: ['dairy'],
  },
  {
    name: 'Coconut Curry Chicken',
    slotCategory: 'main_chicken',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'medium',
    mainProtein: 'chicken',
    cuisine: 'Thai',
    prepTimeMinutes: 20,
    cookTimeMinutes: 30,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/46822/thai-coconut-curry-chicken/',
    ingredients: ['chicken thighs', 'coconut milk', 'curry paste', 'fish sauce', 'brown sugar', 'bell pepper', 'basil', 'lime juice'],
    tags: ['curry', 'coconut', 'thai'],
    allergens: [],
  },

  // ==================== MAIN BEEF (25 dishes) ====================
  {
    name: 'Beef Wellington',
    slotCategory: 'main_beef',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'hard',
    mainProtein: 'beef',
    cuisine: 'British',
    prepTimeMinutes: 60,
    cookTimeMinutes: 45,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/16311/beef-wellington/',
    ingredients: ['beef tenderloin', 'puff pastry', 'mushrooms', 'shallots', 'pate', 'egg', 'dijon mustard', 'prosciutto'],
    tags: ['elegant', 'special occasion', 'wrapped'],
    allergens: ['gluten', 'eggs'],
  },
  {
    name: 'Beef Rendang',
    slotCategory: 'main_beef',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'medium',
    mainProtein: 'beef',
    cuisine: 'Indonesian',
    prepTimeMinutes: 30,
    cookTimeMinutes: 180,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/213475/beef-rendang/',
    ingredients: ['beef chuck', 'coconut milk', 'lemongrass', 'galangal', 'garlic', 'shallots', 'chili', 'turmeric', 'ginger'],
    tags: ['slow-cooked', 'indonesian', 'spicy'],
    allergens: [],
  },
  {
    name: 'Philly Cheesesteak',
    slotCategory: 'main_beef',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'easy',
    mainProtein: 'beef',
    cuisine: 'American',
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/20338/philly-cheesesteak/',
    ingredients: ['ribeye steak', 'provolone cheese', 'hoagie rolls', 'onion', 'bell pepper', 'mushrooms', 'vegetable oil'],
    tags: ['sandwich', 'american', 'cheesy'],
    allergens: ['dairy', 'gluten'],
  },
  {
    name: 'Beef Goulash',
    slotCategory: 'main_beef',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'medium',
    mainProtein: 'beef',
    cuisine: 'Hungarian',
    prepTimeMinutes: 25,
    cookTimeMinutes: 120,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/78202/hungarian-goulash-magyar-gulyas/',
    ingredients: ['beef chuck', 'onions', 'paprika', 'tomatoes', 'beef broth', 'caraway seeds', 'garlic', 'potatoes', 'bell pepper'],
    tags: ['stew', 'hungarian', 'paprika'],
    allergens: [],
  },
  {
    name: 'Mongolian Beef',
    slotCategory: 'main_beef',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'easy',
    mainProtein: 'beef',
    cuisine: 'Chinese-American',
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/229597/quick-mongolian-beef/',
    ingredients: ['flank steak', 'soy sauce', 'brown sugar', 'ginger', 'garlic', 'green onion', 'vegetable oil', 'cornstarch'],
    tags: ['takeout', 'sweet', 'stir-fry'],
    allergens: ['gluten'],
  },
  {
    name: 'Beef Bourguignon',
    slotCategory: 'main_beef',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'hard',
    mainProtein: 'beef',
    cuisine: 'French',
    prepTimeMinutes: 40,
    cookTimeMinutes: 180,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/8436/beef-bourguignon/',
    ingredients: ['beef chuck', 'red wine', 'bacon', 'pearl onions', 'mushrooms', 'carrots', 'beef broth', 'tomato paste', 'thyme', 'bay leaf'],
    tags: ['french', 'braised', 'wine'],
    allergens: [],
  },
  {
    name: 'Carne Asada',
    slotCategory: 'main_beef',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'easy',
    mainProtein: 'beef',
    cuisine: 'Mexican',
    prepTimeMinutes: 20,
    cookTimeMinutes: 15,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/70461/authentic-carne-asada/',
    ingredients: ['flank steak', 'lime juice', 'garlic', 'cilantro', 'jalapeno', 'cumin', 'olive oil', 'orange juice'],
    tags: ['grilled', 'mexican', 'tacos'],
    allergens: [],
  },
  {
    name: 'Swedish Meatballs',
    slotCategory: 'main_beef',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    mainProtein: 'beef',
    cuisine: 'Swedish',
    prepTimeMinutes: 30,
    cookTimeMinutes: 25,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/216564/swedish-meatballs/',
    ingredients: ['ground beef', 'ground pork', 'bread crumbs', 'egg', 'cream', 'onion', 'allspice', 'nutmeg', 'beef broth', 'butter'],
    tags: ['swedish', 'meatballs', 'comfort food'],
    allergens: ['dairy', 'gluten', 'eggs'],
  },
  {
    name: 'Beef Satay',
    slotCategory: 'main_beef',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'easy',
    mainProtein: 'beef',
    cuisine: 'Thai',
    prepTimeMinutes: 25,
    cookTimeMinutes: 10,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/44094/thai-beef-satay/',
    ingredients: ['sirloin steak', 'coconut milk', 'peanut butter', 'soy sauce', 'curry powder', 'garlic', 'lime juice', 'brown sugar'],
    tags: ['skewers', 'grilled', 'thai'],
    allergens: ['nuts', 'gluten'],
  },
  {
    name: 'Shepherd\'s Pie',
    slotCategory: 'main_beef',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    mainProtein: 'beef',
    cuisine: 'British',
    prepTimeMinutes: 30,
    cookTimeMinutes: 45,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/23439/shepherds-pie-vi/',
    ingredients: ['ground beef', 'potatoes', 'butter', 'milk', 'peas', 'carrots', 'corn', 'onion', 'beef broth', 'worcestershire sauce'],
    tags: ['british', 'comfort food', 'casserole'],
    allergens: ['dairy'],
  },
  {
    name: 'Beef Picadillo',
    slotCategory: 'main_beef',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'easy',
    mainProtein: 'beef',
    cuisine: 'Cuban',
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/234679/cuban-beef-picadillo/',
    ingredients: ['ground beef', 'tomatoes', 'olives', 'raisins', 'onion', 'garlic', 'cumin', 'oregano', 'bell pepper'],
    tags: ['cuban', 'one-pot', 'sweet-savory'],
    allergens: [],
  },
  {
    name: 'Bibimbap',
    slotCategory: 'main_beef',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'medium',
    mainProtein: 'beef',
    cuisine: 'Korean',
    prepTimeMinutes: 30,
    cookTimeMinutes: 20,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/70052/bibimbap/',
    ingredients: ['beef sirloin', 'rice', 'spinach', 'carrots', 'zucchini', 'bean sprouts', 'egg', 'gochujang', 'sesame oil', 'garlic'],
    tags: ['korean', 'rice bowl', 'colorful'],
    allergens: ['eggs', 'gluten'],
  },
  {
    name: 'Beef Birria',
    slotCategory: 'main_beef',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'hard',
    mainProtein: 'beef',
    cuisine: 'Mexican',
    prepTimeMinutes: 45,
    cookTimeMinutes: 240,
    servings: 8,
    sourceUrl: 'https://www.allrecipes.com/recipe/282879/birria-de-res/',
    ingredients: ['beef chuck', 'dried chiles', 'tomatoes', 'onion', 'garlic', 'cumin', 'oregano', 'cloves', 'cinnamon', 'beef broth'],
    tags: ['braised', 'mexican', 'tacos'],
    allergens: [],
  },
  {
    name: 'Beef Carpaccio',
    slotCategory: 'main_beef',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'easy',
    mainProtein: 'beef',
    cuisine: 'Italian',
    prepTimeMinutes: 20,
    cookTimeMinutes: 0,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/73447/beef-carpaccio/',
    ingredients: ['beef tenderloin', 'arugula', 'parmesan cheese', 'olive oil', 'lemon juice', 'capers', 'salt', 'pepper'],
    tags: ['raw', 'appetizer', 'italian'],
    allergens: ['dairy'],
  },
  {
    name: 'Cottage Pie',
    slotCategory: 'main_beef',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    mainProtein: 'beef',
    cuisine: 'British',
    prepTimeMinutes: 25,
    cookTimeMinutes: 40,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/15765/cottage-pie-ii/',
    ingredients: ['ground beef', 'potatoes', 'butter', 'milk', 'onion', 'carrots', 'peas', 'tomato paste', 'beef broth', 'thyme'],
    tags: ['british', 'casserole', 'comfort food'],
    allergens: ['dairy'],
  },
  {
    name: 'Beef Barbacoa',
    slotCategory: 'main_beef',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'medium',
    mainProtein: 'beef',
    cuisine: 'Mexican',
    prepTimeMinutes: 20,
    cookTimeMinutes: 240,
    servings: 8,
    sourceUrl: 'https://www.allrecipes.com/recipe/257871/slow-cooker-barbacoa/',
    ingredients: ['beef chuck', 'chipotle peppers', 'lime juice', 'garlic', 'cumin', 'oregano', 'cloves', 'beef broth', 'apple cider vinegar'],
    tags: ['slow-cooker', 'mexican', 'shredded'],
    allergens: [],
  },
  {
    name: 'Italian Beef Sandwich',
    slotCategory: 'main_beef',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    mainProtein: 'beef',
    cuisine: 'American',
    prepTimeMinutes: 20,
    cookTimeMinutes: 240,
    servings: 8,
    sourceUrl: 'https://www.allrecipes.com/recipe/92063/italian-beef-for-sandwiches/',
    ingredients: ['beef roast', 'italian dressing mix', 'pepperoncini', 'beef broth', 'italian rolls', 'provolone cheese', 'giardiniera'],
    tags: ['sandwich', 'chicago', 'slow-cooker'],
    allergens: ['dairy', 'gluten'],
  },
  {
    name: 'Beef Lo Mein',
    slotCategory: 'main_beef',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'easy',
    mainProtein: 'beef',
    cuisine: 'Chinese',
    prepTimeMinutes: 20,
    cookTimeMinutes: 15,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/228194/easy-beef-lo-mein/',
    ingredients: ['sirloin steak', 'lo mein noodles', 'soy sauce', 'sesame oil', 'garlic', 'ginger', 'cabbage', 'carrots', 'green onion'],
    tags: ['noodles', 'takeout', 'chinese'],
    allergens: ['gluten'],
  },
  {
    name: 'Beef Massaman Curry',
    slotCategory: 'main_beef',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'medium',
    mainProtein: 'beef',
    cuisine: 'Thai',
    prepTimeMinutes: 25,
    cookTimeMinutes: 90,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/72135/massaman-curry/',
    ingredients: ['beef chuck', 'coconut milk', 'massaman curry paste', 'potatoes', 'peanuts', 'onion', 'fish sauce', 'brown sugar', 'tamarind'],
    tags: ['curry', 'thai', 'creamy'],
    allergens: ['nuts'],
  },
  {
    name: 'Steak Diane',
    slotCategory: 'main_beef',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    mainProtein: 'beef',
    cuisine: 'French',
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 2,
    sourceUrl: 'https://www.allrecipes.com/recipe/76863/steak-diane/',
    ingredients: ['filet mignon', 'butter', 'shallots', 'mushrooms', 'brandy', 'cream', 'dijon mustard', 'worcestershire sauce', 'parsley'],
    tags: ['pan-seared', 'fancy', 'steakhouse'],
    allergens: ['dairy'],
  },
  {
    name: 'Chili Con Carne',
    slotCategory: 'main_beef',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'medium',
    mainProtein: 'beef',
    cuisine: 'Tex-Mex',
    prepTimeMinutes: 20,
    cookTimeMinutes: 90,
    servings: 8,
    sourceUrl: 'https://www.allrecipes.com/recipe/14231/easy-chili/',
    ingredients: ['ground beef', 'kidney beans', 'tomatoes', 'onion', 'garlic', 'chili powder', 'cumin', 'oregano', 'cayenne'],
    tags: ['chili', 'tex-mex', 'spicy'],
    allergens: [],
  },
  {
    name: 'Beef Negimaki',
    slotCategory: 'main_beef',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'medium',
    mainProtein: 'beef',
    cuisine: 'Japanese',
    prepTimeMinutes: 30,
    cookTimeMinutes: 10,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/25328/negimaki/',
    ingredients: ['sirloin steak', 'green onion', 'soy sauce', 'mirin', 'sake', 'sugar', 'ginger', 'sesame seeds'],
    tags: ['rolled', 'japanese', 'appetizer'],
    allergens: ['gluten'],
  },
  {
    name: 'Beef Enchiladas',
    slotCategory: 'main_beef',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    mainProtein: 'beef',
    cuisine: 'Mexican',
    prepTimeMinutes: 25,
    cookTimeMinutes: 30,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/70448/simple-beef-enchiladas/',
    ingredients: ['ground beef', 'corn tortillas', 'enchilada sauce', 'cheddar cheese', 'onion', 'garlic', 'cumin', 'sour cream'],
    tags: ['mexican', 'cheesy', 'baked'],
    allergens: ['dairy', 'gluten'],
  },
  {
    name: 'Beef Rogan Josh',
    slotCategory: 'main_beef',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'medium',
    mainProtein: 'beef',
    cuisine: 'Indian',
    prepTimeMinutes: 30,
    cookTimeMinutes: 90,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/72051/rogan-josh/',
    ingredients: ['beef chuck', 'yogurt', 'tomatoes', 'onion', 'garlic', 'ginger', 'kashmiri chili', 'garam masala', 'cardamom', 'cinnamon'],
    tags: ['indian', 'curry', 'aromatic'],
    allergens: ['dairy'],
  },
  {
    name: 'Steak Frites',
    slotCategory: 'main_beef',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    mainProtein: 'beef',
    cuisine: 'French',
    prepTimeMinutes: 20,
    cookTimeMinutes: 30,
    servings: 2,
    sourceUrl: 'https://www.allrecipes.com/recipe/236643/steak-frites/',
    ingredients: ['ribeye steak', 'potatoes', 'butter', 'salt', 'pepper', 'thyme', 'garlic', 'vegetable oil', 'parsley'],
    tags: ['french', 'bistro', 'classic'],
    allergens: ['dairy'],
  },

  // ==================== SIDE VEG (25 dishes) ====================
  {
    name: 'Garlic Sauteed Spinach',
    slotCategory: 'side_veg',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 5,
    cookTimeMinutes: 5,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/195795/garlic-spinach/',
    ingredients: ['spinach', 'garlic', 'olive oil', 'salt', 'pepper', 'lemon juice'],
    tags: ['healthy', 'quick', 'side'],
    allergens: [],
  },
  {
    name: 'Roasted Balsamic Vegetables',
    slotCategory: 'side_veg',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 35,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/70934/balsamic-roasted-vegetables/',
    ingredients: ['zucchini', 'bell peppers', 'red onion', 'cherry tomatoes', 'balsamic vinegar', 'olive oil', 'garlic', 'basil'],
    tags: ['roasted', 'mediterranean', 'colorful'],
    allergens: [],
  },
  {
    name: 'Creamy Coleslaw',
    slotCategory: 'side_veg',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 0,
    servings: 8,
    sourceUrl: 'https://www.allrecipes.com/recipe/50416/creamy-coleslaw/',
    ingredients: ['cabbage', 'carrots', 'mayonnaise', 'sugar', 'apple cider vinegar', 'celery seeds', 'salt', 'pepper'],
    tags: ['bbq', 'summer', 'creamy'],
    allergens: ['eggs'],
  },
  {
    name: 'Grilled Zucchini',
    slotCategory: 'side_veg',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/14574/grilled-zucchini/',
    ingredients: ['zucchini', 'olive oil', 'garlic', 'italian seasoning', 'salt', 'pepper', 'parmesan cheese'],
    tags: ['grilled', 'summer', 'healthy'],
    allergens: ['dairy'],
  },
  {
    name: 'Caprese Salad',
    slotCategory: 'side_veg',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/21235/insalata-caprese/',
    ingredients: ['tomatoes', 'mozzarella cheese', 'fresh basil', 'olive oil', 'balsamic vinegar', 'salt', 'pepper'],
    tags: ['italian', 'fresh', 'summer'],
    allergens: ['dairy'],
  },
  {
    name: 'Sauteed Mushrooms',
    slotCategory: 'side_veg',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/165649/sauteed-mushrooms/',
    ingredients: ['cremini mushrooms', 'butter', 'garlic', 'thyme', 'white wine', 'parsley', 'salt', 'pepper'],
    tags: ['steakhouse', 'side', 'savory'],
    allergens: ['dairy'],
  },
  {
    name: 'Cucumber Salad',
    slotCategory: 'side_veg',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 0,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/17086/cucumbers-and-onions/',
    ingredients: ['cucumber', 'red onion', 'rice vinegar', 'sugar', 'sesame oil', 'salt', 'sesame seeds', 'chili flakes'],
    tags: ['asian', 'refreshing', 'light'],
    allergens: [],
  },
  {
    name: 'Roasted Butternut Squash',
    slotCategory: 'side_veg',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 40,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/219756/roasted-butternut-squash/',
    ingredients: ['butternut squash', 'olive oil', 'maple syrup', 'cinnamon', 'nutmeg', 'salt', 'pepper'],
    tags: ['fall', 'sweet', 'roasted'],
    allergens: [],
  },
  {
    name: 'Caesar Salad',
    slotCategory: 'side_veg',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 0,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/229063/classic-caesar-salad/',
    ingredients: ['romaine lettuce', 'parmesan cheese', 'croutons', 'caesar dressing', 'lemon juice', 'anchovies', 'garlic'],
    tags: ['classic', 'salad', 'creamy'],
    allergens: ['dairy', 'gluten'],
  },
  {
    name: 'Charred Broccolini',
    slotCategory: 'side_veg',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/242643/charred-broccolini/',
    ingredients: ['broccolini', 'olive oil', 'garlic', 'lemon zest', 'red pepper flakes', 'salt'],
    tags: ['charred', 'healthy', 'quick'],
    allergens: [],
  },
  {
    name: 'Greek Salad',
    slotCategory: 'side_veg',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 0,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/14376/greek-salad-i/',
    ingredients: ['cucumber', 'tomatoes', 'red onion', 'kalamata olives', 'feta cheese', 'olive oil', 'oregano', 'lemon juice'],
    tags: ['mediterranean', 'fresh', 'healthy'],
    allergens: ['dairy'],
  },
  {
    name: 'Glazed Carrots',
    slotCategory: 'side_veg',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/23653/brown-sugar-glazed-carrots/',
    ingredients: ['carrots', 'butter', 'brown sugar', 'salt', 'pepper', 'parsley'],
    tags: ['sweet', 'holiday', 'classic'],
    allergens: ['dairy'],
  },
  {
    name: 'Sauteed Kale',
    slotCategory: 'side_veg',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/176957/sauteed-kale/',
    ingredients: ['kale', 'olive oil', 'garlic', 'red pepper flakes', 'lemon juice', 'salt'],
    tags: ['healthy', 'superfood', 'quick'],
    allergens: [],
  },
  {
    name: 'Stuffed Mushrooms',
    slotCategory: 'side_veg',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    prepTimeMinutes: 20,
    cookTimeMinutes: 25,
    servings: 8,
    sourceUrl: 'https://www.allrecipes.com/recipe/14725/stuffed-mushrooms-iii/',
    ingredients: ['cremini mushrooms', 'cream cheese', 'garlic', 'parmesan cheese', 'bread crumbs', 'parsley', 'butter'],
    tags: ['appetizer', 'party', 'stuffed'],
    allergens: ['dairy', 'gluten'],
  },
  {
    name: 'Corn on the Cob',
    slotCategory: 'side_veg',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/222352/grilled-corn-on-the-cob/',
    ingredients: ['corn', 'butter', 'salt', 'pepper', 'lime', 'chili powder'],
    tags: ['summer', 'bbq', 'grilled'],
    allergens: ['dairy'],
  },
  {
    name: 'Roasted Tomatoes',
    slotCategory: 'side_veg',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 45,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/24234/roasted-tomatoes/',
    ingredients: ['roma tomatoes', 'olive oil', 'garlic', 'thyme', 'salt', 'pepper', 'balsamic vinegar'],
    tags: ['roasted', 'italian', 'simple'],
    allergens: [],
  },
  {
    name: 'Sesame Green Beans',
    slotCategory: 'side_veg',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/14052/sesame-green-beans/',
    ingredients: ['green beans', 'sesame oil', 'soy sauce', 'garlic', 'sesame seeds', 'ginger'],
    tags: ['asian', 'healthy', 'quick'],
    allergens: ['gluten'],
  },
  {
    name: 'Waldorf Salad',
    slotCategory: 'side_veg',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 0,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/14469/waldorf-salad-ii/',
    ingredients: ['apples', 'celery', 'walnuts', 'grapes', 'mayonnaise', 'lemon juice', 'lettuce'],
    tags: ['classic', 'crunchy', 'fruity'],
    allergens: ['eggs', 'nuts'],
  },
  {
    name: 'Roasted Fennel',
    slotCategory: 'side_veg',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 35,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/83053/roasted-fennel/',
    ingredients: ['fennel bulbs', 'olive oil', 'garlic', 'lemon juice', 'parmesan cheese', 'salt', 'pepper'],
    tags: ['italian', 'roasted', 'unique'],
    allergens: ['dairy'],
  },
  {
    name: 'Bacon Brussels Sprouts',
    slotCategory: 'side_veg',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/228651/bacon-brussels-sprouts/',
    ingredients: ['brussels sprouts', 'bacon', 'garlic', 'balsamic vinegar', 'salt', 'pepper'],
    tags: ['bacon', 'roasted', 'holiday'],
    allergens: [],
  },
  {
    name: 'Mexican Street Corn',
    slotCategory: 'side_veg',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/169931/mexican-street-corn-elotes/',
    ingredients: ['corn', 'mayonnaise', 'cotija cheese', 'chili powder', 'lime', 'cilantro', 'garlic'],
    tags: ['mexican', 'grilled', 'street food'],
    allergens: ['dairy', 'eggs'],
  },
  {
    name: 'Parmesan Asparagus',
    slotCategory: 'side_veg',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/228730/parmesan-roasted-asparagus/',
    ingredients: ['asparagus', 'parmesan cheese', 'olive oil', 'garlic', 'lemon zest', 'salt', 'pepper'],
    tags: ['roasted', 'cheesy', 'elegant'],
    allergens: ['dairy'],
  },
  {
    name: 'Pickled Red Onions',
    slotCategory: 'side_veg',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 5,
    servings: 8,
    sourceUrl: 'https://www.allrecipes.com/recipe/238538/quick-pickled-red-onions/',
    ingredients: ['red onion', 'apple cider vinegar', 'sugar', 'salt', 'peppercorns', 'bay leaf'],
    tags: ['pickled', 'condiment', 'tangy'],
    allergens: [],
  },
  {
    name: 'Cauliflower Mash',
    slotCategory: 'side_veg',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/246681/cauliflower-mashed-potatoes/',
    ingredients: ['cauliflower', 'butter', 'cream', 'garlic', 'chives', 'salt', 'pepper'],
    tags: ['low-carb', 'keto', 'healthy'],
    allergens: ['dairy'],
  },
  {
    name: 'Edamame',
    slotCategory: 'side_veg',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 5,
    cookTimeMinutes: 5,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/80048/easy-edamame/',
    ingredients: ['edamame', 'sea salt', 'garlic', 'sesame oil'],
    tags: ['japanese', 'healthy', 'snack'],
    allergens: [],
  },

  // ==================== SIDE STARCH (25 dishes) ====================
  {
    name: 'Garlic Parmesan Risotto',
    slotCategory: 'side_starch',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    prepTimeMinutes: 10,
    cookTimeMinutes: 30,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/85389/gourmet-mushroom-risotto/',
    ingredients: ['arborio rice', 'chicken broth', 'parmesan cheese', 'butter', 'garlic', 'white wine', 'onion', 'parsley'],
    tags: ['italian', 'creamy', 'comfort food'],
    allergens: ['dairy'],
  },
  {
    name: 'Hasselback Potatoes',
    slotCategory: 'side_starch',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    prepTimeMinutes: 15,
    cookTimeMinutes: 60,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/239979/hasselback-potatoes/',
    ingredients: ['potatoes', 'butter', 'garlic', 'parmesan cheese', 'thyme', 'salt', 'pepper'],
    tags: ['swedish', 'crispy', 'fancy'],
    allergens: ['dairy'],
  },
  {
    name: 'Coconut Rice',
    slotCategory: 'side_starch',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 5,
    cookTimeMinutes: 20,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/25861/coconut-rice/',
    ingredients: ['jasmine rice', 'coconut milk', 'water', 'sugar', 'salt'],
    tags: ['thai', 'sweet', 'tropical'],
    allergens: [],
  },
  {
    name: 'Twice Baked Potatoes',
    slotCategory: 'side_starch',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    prepTimeMinutes: 20,
    cookTimeMinutes: 90,
    servings: 8,
    sourceUrl: 'https://www.allrecipes.com/recipe/19887/twice-baked-potatoes/',
    ingredients: ['potatoes', 'butter', 'sour cream', 'cheddar cheese', 'bacon', 'chives', 'salt', 'pepper'],
    tags: ['loaded', 'cheesy', 'steakhouse'],
    allergens: ['dairy'],
  },
  {
    name: 'Spanish Rice',
    slotCategory: 'side_starch',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/27072/spanish-rice-ii/',
    ingredients: ['rice', 'tomato sauce', 'chicken broth', 'onion', 'garlic', 'cumin', 'chili powder'],
    tags: ['mexican', 'tomato', 'flavorful'],
    allergens: [],
  },
  {
    name: 'Garlic Naan Bread',
    slotCategory: 'side_starch',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    prepTimeMinutes: 90,
    cookTimeMinutes: 15,
    servings: 8,
    sourceUrl: 'https://www.allrecipes.com/recipe/14565/naan/',
    ingredients: ['flour', 'yogurt', 'yeast', 'sugar', 'salt', 'garlic', 'butter', 'cilantro'],
    tags: ['indian', 'bread', 'garlic'],
    allergens: ['dairy', 'gluten'],
  },
  {
    name: 'Duchess Potatoes',
    slotCategory: 'side_starch',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    prepTimeMinutes: 25,
    cookTimeMinutes: 25,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/231609/duchess-potatoes/',
    ingredients: ['potatoes', 'butter', 'egg yolks', 'cream', 'nutmeg', 'salt', 'pepper'],
    tags: ['french', 'elegant', 'holiday'],
    allergens: ['dairy', 'eggs'],
  },
  {
    name: 'Cilantro Lime Rice',
    slotCategory: 'side_starch',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 5,
    cookTimeMinutes: 20,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/146734/cilantro-lime-rice/',
    ingredients: ['rice', 'lime juice', 'lime zest', 'cilantro', 'butter', 'salt'],
    tags: ['mexican', 'fresh', 'chipotle-style'],
    allergens: ['dairy'],
  },
  {
    name: 'Sweet Potato Casserole',
    slotCategory: 'side_starch',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    prepTimeMinutes: 25,
    cookTimeMinutes: 45,
    servings: 8,
    sourceUrl: 'https://www.allrecipes.com/recipe/21261/yummy-sweet-potato-casserole/',
    ingredients: ['sweet potatoes', 'butter', 'brown sugar', 'eggs', 'milk', 'pecans', 'marshmallows', 'cinnamon'],
    tags: ['thanksgiving', 'sweet', 'holiday'],
    allergens: ['dairy', 'eggs', 'nuts'],
  },
  {
    name: 'Saffron Rice',
    slotCategory: 'side_starch',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/76809/saffron-rice/',
    ingredients: ['basmati rice', 'saffron', 'butter', 'chicken broth', 'onion', 'salt'],
    tags: ['persian', 'aromatic', 'golden'],
    allergens: ['dairy'],
  },
  {
    name: 'Yorkshire Pudding',
    slotCategory: 'side_starch',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 12,
    sourceUrl: 'https://www.allrecipes.com/recipe/16183/yorkshire-pudding/',
    ingredients: ['flour', 'eggs', 'milk', 'salt', 'beef drippings'],
    tags: ['british', 'roast dinner', 'popover'],
    allergens: ['gluten', 'eggs', 'dairy'],
  },
  {
    name: 'Cheesy Grits',
    slotCategory: 'side_starch',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'easy',
    prepTimeMinutes: 5,
    cookTimeMinutes: 20,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/25208/cheese-grits/',
    ingredients: ['grits', 'cheddar cheese', 'butter', 'milk', 'garlic', 'salt', 'pepper'],
    tags: ['southern', 'cheesy', 'comfort food'],
    allergens: ['dairy'],
  },
  {
    name: 'Lemon Orzo',
    slotCategory: 'side_starch',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'easy',
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/229886/lemon-orzo-with-parmesan/',
    ingredients: ['orzo pasta', 'lemon juice', 'lemon zest', 'parmesan cheese', 'butter', 'parsley'],
    tags: ['pasta', 'citrus', 'light'],
    allergens: ['dairy', 'gluten'],
  },
  {
    name: 'Potato Gratin',
    slotCategory: 'side_starch',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    prepTimeMinutes: 20,
    cookTimeMinutes: 60,
    servings: 8,
    sourceUrl: 'https://www.allrecipes.com/recipe/23365/scalloped-potatoes-iii/',
    ingredients: ['potatoes', 'heavy cream', 'gruyere cheese', 'garlic', 'thyme', 'nutmeg', 'butter'],
    tags: ['french', 'creamy', 'baked'],
    allergens: ['dairy'],
  },
  {
    name: 'Egg Fried Rice',
    slotCategory: 'side_starch',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/79543/fried-rice-restaurant-style/',
    ingredients: ['rice', 'eggs', 'soy sauce', 'sesame oil', 'green onion', 'peas', 'carrots', 'garlic'],
    tags: ['chinese', 'quick', 'takeout'],
    allergens: ['eggs', 'gluten'],
  },
  {
    name: 'Cornbread',
    slotCategory: 'side_starch',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 9,
    sourceUrl: 'https://www.allrecipes.com/recipe/17891/honey-cornbread/',
    ingredients: ['cornmeal', 'flour', 'sugar', 'butter', 'eggs', 'milk', 'baking powder', 'honey'],
    tags: ['southern', 'bread', 'bbq'],
    allergens: ['dairy', 'gluten', 'eggs'],
  },
  {
    name: 'Roasted Fingerling Potatoes',
    slotCategory: 'side_starch',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 35,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/219709/roasted-fingerling-potatoes/',
    ingredients: ['fingerling potatoes', 'olive oil', 'rosemary', 'garlic', 'salt', 'pepper'],
    tags: ['roasted', 'crispy', 'herbed'],
    allergens: [],
  },
  {
    name: 'Macaroni and Cheese',
    slotCategory: 'side_starch',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    prepTimeMinutes: 15,
    cookTimeMinutes: 35,
    servings: 8,
    sourceUrl: 'https://www.allrecipes.com/recipe/238691/simple-macaroni-and-cheese/',
    ingredients: ['elbow macaroni', 'cheddar cheese', 'butter', 'flour', 'milk', 'mustard powder', 'bread crumbs'],
    tags: ['american', 'cheesy', 'comfort food'],
    allergens: ['dairy', 'gluten'],
  },
  {
    name: 'Pita Bread',
    slotCategory: 'side_starch',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'medium',
    prepTimeMinutes: 90,
    cookTimeMinutes: 15,
    servings: 8,
    sourceUrl: 'https://www.allrecipes.com/recipe/14566/pita-bread/',
    ingredients: ['flour', 'yeast', 'sugar', 'salt', 'olive oil', 'water'],
    tags: ['middle eastern', 'bread', 'pocket'],
    allergens: ['gluten'],
  },
  {
    name: 'Potato Salad',
    slotCategory: 'side_starch',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'easy',
    prepTimeMinutes: 20,
    cookTimeMinutes: 20,
    servings: 8,
    sourceUrl: 'https://www.allrecipes.com/recipe/24325/good-old-fashioned-potato-salad/',
    ingredients: ['potatoes', 'mayonnaise', 'mustard', 'celery', 'onion', 'hard-boiled eggs', 'pickles', 'paprika'],
    tags: ['bbq', 'summer', 'picnic'],
    allergens: ['eggs'],
  },
  {
    name: 'Garlic Bread',
    slotCategory: 'side_starch',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 8,
    sourceUrl: 'https://www.allrecipes.com/recipe/20066/garlic-bread/',
    ingredients: ['french bread', 'butter', 'garlic', 'parsley', 'parmesan cheese'],
    tags: ['italian', 'bread', 'buttery'],
    allergens: ['dairy', 'gluten'],
  },
  {
    name: 'Tabbouleh',
    slotCategory: 'side_starch',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 20,
    cookTimeMinutes: 10,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/15127/traditional-tabbouleh/',
    ingredients: ['bulgur wheat', 'parsley', 'mint', 'tomatoes', 'cucumber', 'lemon juice', 'olive oil', 'green onion'],
    tags: ['lebanese', 'fresh', 'healthy'],
    allergens: ['gluten'],
  },
  {
    name: 'Smashed Potatoes',
    slotCategory: 'side_starch',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 45,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/173212/crispy-smashed-potatoes/',
    ingredients: ['baby potatoes', 'olive oil', 'garlic', 'rosemary', 'salt', 'pepper'],
    tags: ['crispy', 'roasted', 'trendy'],
    allergens: [],
  },
  {
    name: 'Cauliflower Rice',
    slotCategory: 'side_starch',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/239442/cauliflower-rice/',
    ingredients: ['cauliflower', 'olive oil', 'garlic', 'salt', 'pepper', 'parsley'],
    tags: ['low-carb', 'keto', 'healthy'],
    allergens: [],
  },
  {
    name: 'Biscuits',
    slotCategory: 'side_starch',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    servings: 12,
    sourceUrl: 'https://www.allrecipes.com/recipe/20075/basic-biscuits/',
    ingredients: ['flour', 'butter', 'buttermilk', 'baking powder', 'sugar', 'salt'],
    tags: ['southern', 'fluffy', 'bread'],
    allergens: ['dairy', 'gluten'],
  },

  // ==================== SOUP (25 dishes) ====================
  {
    name: 'Tom Yum Soup',
    slotCategory: 'soup',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'medium',
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/228136/authentic-tom-yum-soup/',
    ingredients: ['shrimp', 'lemongrass', 'galangal', 'lime leaves', 'fish sauce', 'lime juice', 'chili', 'mushrooms', 'cilantro'],
    tags: ['thai', 'spicy', 'sour'],
    allergens: [],
  },
  {
    name: 'Clam Chowder',
    slotCategory: 'soup',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    prepTimeMinutes: 20,
    cookTimeMinutes: 40,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/13115/new-england-clam-chowder/',
    ingredients: ['clams', 'potatoes', 'bacon', 'onion', 'celery', 'cream', 'butter', 'flour', 'thyme'],
    tags: ['new england', 'creamy', 'seafood'],
    allergens: ['dairy', 'gluten'],
  },
  {
    name: 'Pho',
    slotCategory: 'soup',
    kosher: true,
    kosherStyle: 'meat',
    difficulty: 'hard',
    mainProtein: 'beef',
    cuisine: 'Vietnamese',
    prepTimeMinutes: 30,
    cookTimeMinutes: 180,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/228443/authentic-pho/',
    ingredients: ['beef bones', 'rice noodles', 'star anise', 'cinnamon', 'cloves', 'ginger', 'onion', 'fish sauce', 'bean sprouts', 'basil', 'lime'],
    tags: ['vietnamese', 'noodle soup', 'aromatic'],
    allergens: [],
  },
  {
    name: 'Tortilla Soup',
    slotCategory: 'soup',
    kosher: true,
    kosherStyle: 'meat',
    mainProtein: 'chicken',
    cuisine: 'Mexican',
    difficulty: 'medium',
    prepTimeMinutes: 20,
    cookTimeMinutes: 30,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/26700/chicken-tortilla-soup/',
    ingredients: ['chicken breast', 'tomatoes', 'chicken broth', 'onion', 'garlic', 'cumin', 'chili powder', 'tortilla strips', 'avocado', 'lime'],
    tags: ['mexican', 'spicy', 'topped'],
    allergens: [],
  },
  {
    name: 'Lobster Bisque',
    slotCategory: 'soup',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'hard',
    cuisine: 'French',
    prepTimeMinutes: 30,
    cookTimeMinutes: 60,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/13219/lobster-bisque/',
    ingredients: ['lobster', 'cream', 'butter', 'sherry', 'tomato paste', 'onion', 'celery', 'carrots', 'thyme', 'bay leaf'],
    tags: ['fancy', 'creamy', 'seafood'],
    allergens: ['dairy'],
  },
  {
    name: 'Egg Drop Soup',
    slotCategory: 'soup',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    cuisine: 'Chinese',
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/19661/egg-drop-soup/',
    ingredients: ['chicken broth', 'eggs', 'cornstarch', 'green onion', 'sesame oil', 'ginger', 'soy sauce'],
    tags: ['chinese', 'quick', 'silky'],
    allergens: ['eggs', 'gluten'],
  },
  {
    name: 'Italian Wedding Soup',
    slotCategory: 'soup',
    kosher: true,
    kosherStyle: 'meat',
    mainProtein: 'beef',
    cuisine: 'Italian',
    difficulty: 'medium',
    prepTimeMinutes: 30,
    cookTimeMinutes: 30,
    servings: 8,
    sourceUrl: 'https://www.allrecipes.com/recipe/22958/italian-wedding-soup-ii/',
    ingredients: ['ground beef', 'ground pork', 'bread crumbs', 'parmesan', 'chicken broth', 'escarole', 'orzo', 'egg', 'onion'],
    tags: ['italian', 'meatballs', 'hearty'],
    allergens: ['gluten', 'dairy', 'eggs'],
  },
  {
    name: 'Hot and Sour Soup',
    slotCategory: 'soup',
    kosher: true,
    kosherStyle: 'meat',
    cuisine: 'Chinese',
    difficulty: 'medium',
    prepTimeMinutes: 20,
    cookTimeMinutes: 20,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/18920/restaurant-style-hot-and-sour-soup/',
    ingredients: ['pork', 'tofu', 'mushrooms', 'bamboo shoots', 'eggs', 'vinegar', 'soy sauce', 'white pepper', 'cornstarch', 'chicken broth'],
    tags: ['chinese', 'tangy', 'spicy'],
    allergens: ['gluten', 'eggs'],
  },
  {
    name: 'Gazpacho',
    slotCategory: 'soup',
    kosher: true,
    kosherStyle: 'pareve',
    cuisine: 'Spanish',
    difficulty: 'easy',
    prepTimeMinutes: 20,
    cookTimeMinutes: 0,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/24265/gazpacho/',
    ingredients: ['tomatoes', 'cucumber', 'bell pepper', 'red onion', 'garlic', 'olive oil', 'sherry vinegar', 'bread', 'salt'],
    tags: ['spanish', 'cold', 'summer'],
    allergens: ['gluten'],
  },
  {
    name: 'Wonton Soup',
    slotCategory: 'soup',
    kosher: false,
    kosherStyle: 'unknown',
    cuisine: 'Chinese',
    difficulty: 'medium',
    prepTimeMinutes: 45,
    cookTimeMinutes: 15,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/20371/wonton-soup/',
    ingredients: ['ground pork', 'shrimp', 'wonton wrappers', 'chicken broth', 'green onion', 'ginger', 'sesame oil', 'soy sauce', 'bok choy'],
    tags: ['chinese', 'dumplings', 'comforting'],
    allergens: ['gluten'],
  },
  {
    name: 'Mulligatawny Soup',
    slotCategory: 'soup',
    kosher: true,
    kosherStyle: 'meat',
    mainProtein: 'chicken',
    cuisine: 'Indian',
    difficulty: 'medium',
    prepTimeMinutes: 20,
    cookTimeMinutes: 40,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/70507/mulligatawny-soup-i/',
    ingredients: ['chicken', 'onion', 'carrots', 'celery', 'apple', 'curry powder', 'rice', 'chicken broth', 'cream', 'lemon juice'],
    tags: ['indian', 'curry', 'creamy'],
    allergens: ['dairy'],
  },
  {
    name: 'Pozole',
    slotCategory: 'soup',
    kosher: true,
    kosherStyle: 'meat',
    mainProtein: 'chicken',
    cuisine: 'Mexican',
    difficulty: 'medium',
    prepTimeMinutes: 30,
    cookTimeMinutes: 90,
    servings: 8,
    sourceUrl: 'https://www.allrecipes.com/recipe/72615/pozole-rojo/',
    ingredients: ['pork shoulder', 'hominy', 'dried chiles', 'onion', 'garlic', 'oregano', 'cabbage', 'radishes', 'lime'],
    tags: ['mexican', 'hominy', 'festive'],
    allergens: [],
  },
  {
    name: 'Ribollita',
    slotCategory: 'soup',
    kosher: true,
    kosherStyle: 'pareve',
    cuisine: 'Italian',
    difficulty: 'medium',
    prepTimeMinutes: 25,
    cookTimeMinutes: 60,
    servings: 8,
    sourceUrl: 'https://www.allrecipes.com/recipe/228899/ribollita/',
    ingredients: ['cannellini beans', 'kale', 'cabbage', 'tomatoes', 'bread', 'carrots', 'celery', 'onion', 'garlic', 'parmesan rind'],
    tags: ['tuscan', 'bread soup', 'rustic'],
    allergens: ['gluten'],
  },
  {
    name: 'Avgolemono',
    slotCategory: 'soup',
    kosher: true,
    kosherStyle: 'meat',
    mainProtein: 'chicken',
    cuisine: 'Greek',
    difficulty: 'medium',
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/42059/avgolemono-soup/',
    ingredients: ['chicken', 'chicken broth', 'rice', 'eggs', 'lemon juice', 'dill', 'salt', 'pepper'],
    tags: ['greek', 'lemony', 'silky'],
    allergens: ['eggs'],
  },
  {
    name: 'Corn Chowder',
    slotCategory: 'soup',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/24199/corn-chowder/',
    ingredients: ['corn', 'potatoes', 'bacon', 'onion', 'cream', 'butter', 'chicken broth', 'thyme'],
    tags: ['creamy', 'comfort food', 'summer'],
    allergens: ['dairy'],
  },
  {
    name: 'Miso Soup',
    slotCategory: 'soup',
    kosher: true,
    kosherStyle: 'pareve',
    cuisine: 'Japanese',
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/13107/miso-soup/',
    ingredients: ['miso paste', 'dashi', 'tofu', 'wakame seaweed', 'green onion'],
    tags: ['japanese', 'umami', 'healthy'],
    allergens: [],
  },
  {
    name: 'Black Bean Soup',
    slotCategory: 'soup',
    kosher: true,
    kosherStyle: 'pareve',
    cuisine: 'Cuban',
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 45,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/13416/black-bean-soup/',
    ingredients: ['black beans', 'onion', 'garlic', 'cumin', 'oregano', 'vegetable broth', 'lime juice', 'cilantro', 'sour cream'],
    tags: ['cuban', 'vegetarian', 'hearty'],
    allergens: ['dairy'],
  },
  {
    name: 'Cream of Mushroom Soup',
    slotCategory: 'soup',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/13296/cream-of-mushroom-soup/',
    ingredients: ['mushrooms', 'butter', 'onion', 'garlic', 'flour', 'chicken broth', 'cream', 'thyme', 'sherry'],
    tags: ['creamy', 'earthy', 'comfort food'],
    allergens: ['dairy', 'gluten'],
  },
  {
    name: 'Albondigas Soup',
    slotCategory: 'soup',
    kosher: true,
    kosherStyle: 'meat',
    mainProtein: 'beef',
    cuisine: 'Mexican',
    difficulty: 'medium',
    prepTimeMinutes: 30,
    cookTimeMinutes: 40,
    servings: 8,
    sourceUrl: 'https://www.allrecipes.com/recipe/34510/albondigas/',
    ingredients: ['ground beef', 'rice', 'egg', 'mint', 'tomatoes', 'carrots', 'potatoes', 'zucchini', 'cilantro', 'beef broth'],
    tags: ['mexican', 'meatball soup', 'hearty'],
    allergens: ['eggs'],
  },
  {
    name: 'Broccoli Cheddar Soup',
    slotCategory: 'soup',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/222721/broccoli-cheese-soup/',
    ingredients: ['broccoli', 'cheddar cheese', 'butter', 'flour', 'chicken broth', 'milk', 'carrots', 'onion'],
    tags: ['cheesy', 'comfort food', 'panera-style'],
    allergens: ['dairy', 'gluten'],
  },
  {
    name: 'Ramen',
    slotCategory: 'soup',
    kosher: false,
    kosherStyle: 'unknown',
    mainProtein: 'chicken',
    cuisine: 'Japanese',
    difficulty: 'hard',
    prepTimeMinutes: 60,
    cookTimeMinutes: 240,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/236212/authentic-homemade-ramen/',
    ingredients: ['pork belly', 'ramen noodles', 'soft-boiled egg', 'green onion', 'nori', 'pork broth', 'soy sauce', 'mirin', 'ginger', 'garlic'],
    tags: ['japanese', 'noodle soup', 'rich'],
    allergens: ['gluten', 'eggs'],
  },
  {
    name: 'Beet Borscht',
    slotCategory: 'soup',
    kosher: true,
    kosherStyle: 'pareve',
    cuisine: 'Eastern European',
    difficulty: 'medium',
    prepTimeMinutes: 20,
    cookTimeMinutes: 60,
    servings: 8,
    sourceUrl: 'https://www.allrecipes.com/recipe/84090/borscht-i/',
    ingredients: ['beets', 'cabbage', 'potatoes', 'carrots', 'onion', 'tomato paste', 'beef broth', 'dill', 'sour cream', 'vinegar'],
    tags: ['eastern european', 'beet', 'hearty'],
    allergens: ['dairy'],
  },
  {
    name: 'Laksa',
    slotCategory: 'soup',
    kosher: false,
    kosherStyle: 'unknown',
    cuisine: 'Malaysian',
    difficulty: 'medium',
    prepTimeMinutes: 25,
    cookTimeMinutes: 30,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/257079/authentic-malaysian-laksa/',
    ingredients: ['rice noodles', 'shrimp', 'tofu puffs', 'coconut milk', 'laksa paste', 'bean sprouts', 'lime', 'cilantro', 'chicken broth'],
    tags: ['malaysian', 'coconut', 'spicy'],
    allergens: [],
  },
  {
    name: 'Chicken Gnocchi Soup',
    slotCategory: 'soup',
    kosher: false,
    kosherStyle: 'unknown',
    mainProtein: 'chicken',
    difficulty: 'medium',
    prepTimeMinutes: 20,
    cookTimeMinutes: 30,
    servings: 6,
    sourceUrl: 'https://www.allrecipes.com/recipe/256026/olive-garden-chicken-gnocchi-soup/',
    ingredients: ['chicken breast', 'gnocchi', 'spinach', 'carrots', 'celery', 'cream', 'chicken broth', 'garlic', 'thyme'],
    tags: ['olive garden', 'creamy', 'comfort food'],
    allergens: ['dairy', 'gluten'],
  },
  {
    name: 'Roasted Red Pepper Soup',
    slotCategory: 'soup',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    servings: 4,
    sourceUrl: 'https://www.allrecipes.com/recipe/23618/roasted-red-pepper-soup/',
    ingredients: ['roasted red peppers', 'vegetable broth', 'onion', 'garlic', 'tomatoes', 'basil', 'olive oil', 'cream'],
    tags: ['roasted', 'vibrant', 'smooth'],
    allergens: ['dairy'],
  },

  // ==================== MUFFINS/DESSERTS (25 dishes) ====================
  {
    name: 'Triple Chocolate Muffins',
    slotCategory: 'muffin',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    servings: 12,
    sourceUrl: 'https://www.allrecipes.com/recipe/23600/to-die-for-double-chocolate-muffins/',
    ingredients: ['flour', 'cocoa powder', 'chocolate chips', 'sugar', 'eggs', 'butter', 'milk', 'baking powder', 'vanilla'],
    tags: ['chocolate', 'decadent', 'rich'],
    allergens: ['dairy', 'gluten', 'eggs'],
  },
  {
    name: 'Morning Glory Muffins',
    slotCategory: 'muffin',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'medium',
    prepTimeMinutes: 20,
    cookTimeMinutes: 25,
    servings: 12,
    sourceUrl: 'https://www.allrecipes.com/recipe/7265/morning-glory-muffins/',
    ingredients: ['flour', 'carrots', 'apple', 'raisins', 'walnuts', 'coconut', 'eggs', 'sugar', 'vegetable oil', 'cinnamon'],
    tags: ['healthy', 'breakfast', 'loaded'],
    allergens: ['gluten', 'eggs', 'nuts'],
  },
  {
    name: 'Peach Cobbler Muffins',
    slotCategory: 'muffin',
    kosher: true,
    kosherStyle: 'dairy',
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 22,
    servings: 12,
    sourceUrl: 'https://www.allrecipes.com/recipe/246959/peach-cobbler-muffins/',
    ingredients: ['flour', 'peaches', 'butter', 'sugar', 'eggs', 'milk', 'cinnamon', 'vanilla', 'brown sugar'],
    tags: ['fruity', 'summer', 'cobbler'],
    allergens: ['dairy', 'gluten', 'eggs'],
  },
  {
    name: 'Red Velvet Cupcakes',
    slotCategory: 'muffin',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    prepTimeMinutes: 20,
    cookTimeMinutes: 22,
    servings: 24,
    sourceUrl: 'https://www.allrecipes.com/recipe/17656/red-velvet-cake/',
    ingredients: ['flour', 'cocoa powder', 'red food coloring', 'buttermilk', 'butter', 'sugar', 'eggs', 'cream cheese', 'powdered sugar'],
    tags: ['red velvet', 'cream cheese frosting', 'festive'],
    allergens: ['dairy', 'gluten', 'eggs'],
  },
  {
    name: 'Coffee Cake Muffins',
    slotCategory: 'muffin',
    kosher: true,
    kosherStyle: 'dairy',
    difficulty: 'medium',
    prepTimeMinutes: 20,
    cookTimeMinutes: 25,
    servings: 12,
    sourceUrl: 'https://www.allrecipes.com/recipe/6899/sour-cream-coffee-cake/',
    ingredients: ['flour', 'butter', 'sugar', 'sour cream', 'eggs', 'cinnamon', 'brown sugar', 'pecans', 'vanilla'],
    tags: ['coffee cake', 'streusel', 'breakfast'],
    allergens: ['dairy', 'gluten', 'eggs', 'nuts'],
  },
  {
    name: 'Snickerdoodle Muffins',
    slotCategory: 'muffin',
    kosher: true,
    kosherStyle: 'dairy',
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 12,
    sourceUrl: 'https://www.allrecipes.com/recipe/241188/snickerdoodle-muffins/',
    ingredients: ['flour', 'butter', 'sugar', 'eggs', 'milk', 'cinnamon', 'cream of tartar', 'vanilla', 'baking powder'],
    tags: ['cinnamon', 'sugar', 'classic'],
    allergens: ['dairy', 'gluten', 'eggs'],
  },
  {
    name: 'Savory Cheese Muffins',
    slotCategory: 'muffin',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 12,
    sourceUrl: 'https://www.allrecipes.com/recipe/215382/savory-cheese-muffins/',
    ingredients: ['flour', 'cheddar cheese', 'butter', 'eggs', 'milk', 'baking powder', 'salt', 'chives'],
    tags: ['savory', 'cheesy', 'brunch'],
    allergens: ['dairy', 'gluten', 'eggs'],
  },
  {
    name: 'Maple Walnut Muffins',
    slotCategory: 'muffin',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 22,
    servings: 12,
    sourceUrl: 'https://www.allrecipes.com/recipe/59490/maple-nut-muffins/',
    ingredients: ['flour', 'maple syrup', 'walnuts', 'butter', 'eggs', 'milk', 'brown sugar', 'vanilla'],
    tags: ['maple', 'fall', 'nutty'],
    allergens: ['dairy', 'gluten', 'eggs', 'nuts'],
  },
  {
    name: 'Espresso Chocolate Muffins',
    slotCategory: 'muffin',
    kosher: true,
    kosherStyle: 'dairy',
    difficulty: 'medium',
    prepTimeMinutes: 15,
    cookTimeMinutes: 22,
    servings: 12,
    sourceUrl: 'https://www.allrecipes.com/recipe/244968/espresso-chocolate-chip-muffins/',
    ingredients: ['flour', 'espresso powder', 'chocolate chips', 'butter', 'sugar', 'eggs', 'sour cream', 'cocoa powder'],
    tags: ['coffee', 'chocolate', 'adult'],
    allergens: ['dairy', 'gluten', 'eggs'],
  },
  {
    name: 'Strawberry Shortcake Muffins',
    slotCategory: 'muffin',
    kosher: true,
    kosherStyle: 'dairy',
    difficulty: 'medium',
    prepTimeMinutes: 20,
    cookTimeMinutes: 25,
    servings: 12,
    sourceUrl: 'https://www.allrecipes.com/recipe/240795/strawberry-shortcake-muffins/',
    ingredients: ['flour', 'strawberries', 'butter', 'sugar', 'eggs', 'cream', 'vanilla', 'baking powder'],
    tags: ['berry', 'summer', 'shortcake'],
    allergens: ['dairy', 'gluten', 'eggs'],
  },
  {
    name: 'Gingerbread Muffins',
    slotCategory: 'muffin',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 22,
    servings: 12,
    sourceUrl: 'https://www.allrecipes.com/recipe/20173/gingerbread-muffins/',
    ingredients: ['flour', 'molasses', 'ginger', 'cinnamon', 'cloves', 'butter', 'eggs', 'sugar', 'buttermilk'],
    tags: ['holiday', 'spiced', 'winter'],
    allergens: ['dairy', 'gluten', 'eggs'],
  },
  {
    name: 'Almond Poppy Seed Muffins',
    slotCategory: 'muffin',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 12,
    sourceUrl: 'https://www.allrecipes.com/recipe/6864/poppy-seed-muffins/',
    ingredients: ['flour', 'poppy seeds', 'almond extract', 'butter', 'sugar', 'eggs', 'milk', 'lemon zest'],
    tags: ['almond', 'poppy seed', 'light'],
    allergens: ['dairy', 'gluten', 'eggs', 'nuts'],
  },
  {
    name: 'Chai Spice Muffins',
    slotCategory: 'muffin',
    kosher: true,
    kosherStyle: 'dairy',
    difficulty: 'medium',
    prepTimeMinutes: 15,
    cookTimeMinutes: 22,
    servings: 12,
    sourceUrl: 'https://www.allrecipes.com/recipe/246957/chai-tea-muffins/',
    ingredients: ['flour', 'chai spice', 'butter', 'sugar', 'eggs', 'milk', 'cinnamon', 'cardamom', 'ginger', 'vanilla'],
    tags: ['chai', 'spiced', 'cozy'],
    allergens: ['dairy', 'gluten', 'eggs'],
  },
  {
    name: 'Coconut Muffins',
    slotCategory: 'muffin',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 22,
    servings: 12,
    sourceUrl: 'https://www.allrecipes.com/recipe/6823/coconut-muffins/',
    ingredients: ['flour', 'shredded coconut', 'coconut milk', 'butter', 'sugar', 'eggs', 'vanilla'],
    tags: ['tropical', 'coconut', 'sweet'],
    allergens: ['dairy', 'gluten', 'eggs'],
  },
  {
    name: 'Raspberry White Chocolate Muffins',
    slotCategory: 'muffin',
    kosher: true,
    kosherStyle: 'dairy',
    difficulty: 'medium',
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    servings: 12,
    sourceUrl: 'https://www.allrecipes.com/recipe/59406/raspberry-and-white-chocolate-muffins/',
    ingredients: ['flour', 'raspberries', 'white chocolate chips', 'butter', 'sugar', 'eggs', 'sour cream', 'vanilla'],
    tags: ['berry', 'chocolate', 'fancy'],
    allergens: ['dairy', 'gluten', 'eggs'],
  },
  {
    name: 'Sweet Potato Muffins',
    slotCategory: 'muffin',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'medium',
    prepTimeMinutes: 20,
    cookTimeMinutes: 25,
    servings: 12,
    sourceUrl: 'https://www.allrecipes.com/recipe/20489/sweet-potato-muffins/',
    ingredients: ['flour', 'sweet potato', 'brown sugar', 'butter', 'eggs', 'cinnamon', 'nutmeg', 'pecans'],
    tags: ['fall', 'sweet potato', 'thanksgiving'],
    allergens: ['dairy', 'gluten', 'eggs', 'nuts'],
  },
  {
    name: 'Orange Cranberry Muffins',
    slotCategory: 'muffin',
    kosher: true,
    kosherStyle: 'dairy',
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 22,
    servings: 12,
    sourceUrl: 'https://www.allrecipes.com/recipe/7372/orange-cranberry-muffins/',
    ingredients: ['flour', 'cranberries', 'orange zest', 'orange juice', 'butter', 'sugar', 'eggs', 'milk'],
    tags: ['citrus', 'berry', 'holiday'],
    allergens: ['dairy', 'gluten', 'eggs'],
  },
  {
    name: 'Peanut Butter Banana Muffins',
    slotCategory: 'muffin',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 12,
    sourceUrl: 'https://www.allrecipes.com/recipe/240619/peanut-butter-banana-muffins/',
    ingredients: ['flour', 'peanut butter', 'bananas', 'butter', 'sugar', 'eggs', 'milk', 'chocolate chips'],
    tags: ['peanut butter', 'banana', 'protein'],
    allergens: ['dairy', 'gluten', 'eggs', 'nuts'],
  },
  {
    name: 'Carrot Cake Cupcakes',
    slotCategory: 'muffin',
    kosher: false,
    kosherStyle: 'unknown',
    difficulty: 'medium',
    prepTimeMinutes: 25,
    cookTimeMinutes: 25,
    servings: 24,
    sourceUrl: 'https://www.allrecipes.com/recipe/150327/carrot-cake-cupcakes/',
    ingredients: ['flour', 'carrots', 'walnuts', 'raisins', 'cream cheese', 'butter', 'sugar', 'eggs', 'cinnamon', 'powdered sugar'],
    tags: ['carrot cake', 'frosted', 'spiced'],
    allergens: ['dairy', 'gluten', 'eggs', 'nuts'],
  },
  {
    name: 'Lemon Drizzle Muffins',
    slotCategory: 'muffin',
    kosher: true,
    kosherStyle: 'dairy',
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 22,
    servings: 12,
    sourceUrl: 'https://www.allrecipes.com/recipe/232770/lemon-drizzle-muffins/',
    ingredients: ['flour', 'lemon juice', 'lemon zest', 'butter', 'sugar', 'eggs', 'milk', 'powdered sugar'],
    tags: ['lemon', 'glazed', 'citrus'],
    allergens: ['dairy', 'gluten', 'eggs'],
  },
  {
    name: 'Apple Cinnamon Crumb Muffins',
    slotCategory: 'muffin',
    kosher: true,
    kosherStyle: 'dairy',
    difficulty: 'medium',
    prepTimeMinutes: 20,
    cookTimeMinutes: 25,
    servings: 12,
    sourceUrl: 'https://www.allrecipes.com/recipe/23541/apple-crumb-muffins/',
    ingredients: ['flour', 'apples', 'cinnamon', 'butter', 'brown sugar', 'sugar', 'eggs', 'milk', 'oats'],
    tags: ['apple', 'crumb topping', 'fall'],
    allergens: ['dairy', 'gluten', 'eggs'],
  },
  {
    name: 'Brownie Muffins',
    slotCategory: 'muffin',
    kosher: true,
    kosherStyle: 'dairy',
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 12,
    sourceUrl: 'https://www.allrecipes.com/recipe/68417/brownie-muffins/',
    ingredients: ['butter', 'chocolate', 'sugar', 'eggs', 'flour', 'vanilla', 'walnuts'],
    tags: ['brownie', 'fudgy', 'chocolate'],
    allergens: ['dairy', 'gluten', 'eggs', 'nuts'],
  },
  {
    name: 'Blackberry Muffins',
    slotCategory: 'muffin',
    kosher: true,
    kosherStyle: 'dairy',
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 22,
    servings: 12,
    sourceUrl: 'https://www.allrecipes.com/recipe/7051/blackberry-muffins/',
    ingredients: ['flour', 'blackberries', 'butter', 'sugar', 'eggs', 'milk', 'vanilla', 'lemon zest'],
    tags: ['berry', 'summer', 'fruity'],
    allergens: ['dairy', 'gluten', 'eggs'],
  },
  {
    name: 'Pistachio Muffins',
    slotCategory: 'muffin',
    kosher: true,
    kosherStyle: 'pareve',
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 22,
    servings: 12,
    sourceUrl: 'https://www.allrecipes.com/recipe/6912/pistachio-muffins/',
    ingredients: ['flour', 'pistachio pudding mix', 'pistachios', 'butter', 'eggs', 'sour cream', 'vegetable oil'],
    tags: ['pistachio', 'green', 'nutty'],
    allergens: ['dairy', 'gluten', 'eggs', 'nuts'],
  },
  {
    name: 'Cornmeal Blueberry Muffins',
    slotCategory: 'muffin',
    kosher: true,
    kosherStyle: 'dairy',
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 22,
    servings: 12,
    sourceUrl: 'https://www.allrecipes.com/recipe/16952/cornmeal-blueberry-muffins/',
    ingredients: ['flour', 'cornmeal', 'blueberries', 'butter', 'sugar', 'eggs', 'buttermilk', 'honey'],
    tags: ['cornmeal', 'berry', 'southern'],
    allergens: ['dairy', 'gluten', 'eggs'],
  },
];

async function getOrCreateIngredient(name: string): Promise<string> {
  const normalizedName = name.toLowerCase().trim();
  
  let ingredient = await prisma.ingredient.findUnique({
    where: { name: normalizedName }
  });

  if (!ingredient) {
    ingredient = await prisma.ingredient.create({
      data: { name: normalizedName }
    });
  }

  return ingredient.id;
}

async function getOrCreateTag(name: string): Promise<string> {
  const normalizedName = name.toLowerCase().trim();
  
  let tag = await prisma.tag.findUnique({
    where: { name: normalizedName }
  });

  if (!tag) {
    tag = await prisma.tag.create({
      data: { name: normalizedName }
    });
  }

  return tag.id;
}

async function getOrCreateAllergen(name: string): Promise<string> {
  const normalizedName = name.toLowerCase().trim();
  
  let allergen = await prisma.allergen.findUnique({
    where: { name: normalizedName }
  });

  if (!allergen) {
    allergen = await prisma.allergen.create({
      data: { name: normalizedName }
    });
  }

  return allergen.id;
}

async function addDishes() {
  console.log('🍽️  Adding 150 new dishes to the database...\n');

  let added = 0;
  let skipped = 0;
  let errors = 0;

  for (const dishData of newDishes) {
    try {
      // Check if dish already exists
      const existing = await prisma.dish.findFirst({
        where: {
          name: dishData.name,
          slotCategory: dishData.slotCategory
        }
      });

      if (existing) {
        console.log(`  ⏭️  Skipped (exists): ${dishData.name}`);
        skipped++;
        continue;
      }

      // Create the dish
      const dish = await prisma.dish.create({
        data: {
          name: dishData.name,
          slotCategory: dishData.slotCategory,
          kosher: dishData.kosher,
          kosherStyle: dishData.kosherStyle,
          difficulty: dishData.difficulty,
          mainProtein: dishData.mainProtein,
          cuisine: dishData.cuisine,
          prepTimeMinutes: dishData.prepTimeMinutes,
          cookTimeMinutes: dishData.cookTimeMinutes,
          servings: dishData.servings,
          sourceUrl: dishData.sourceUrl,
        }
      });

      // Add ingredients
      for (const ingredientName of dishData.ingredients) {
        const ingredientId = await getOrCreateIngredient(ingredientName);
        await prisma.dishIngredient.create({
          data: {
            dishId: dish.id,
            ingredientId: ingredientId
          }
        });
      }

      // Add tags
      for (const tagName of dishData.tags) {
        const tagId = await getOrCreateTag(tagName);
        await prisma.dishTag.create({
          data: {
            dishId: dish.id,
            tagId: tagId
          }
        });
      }

      // Add allergens
      for (const allergenName of dishData.allergens) {
        const allergenId = await getOrCreateAllergen(allergenName);
        await prisma.dishAllergen.create({
          data: {
            dishId: dish.id,
            allergenId: allergenId
          }
        });
      }

      const kosherStatus = dishData.kosher ? '✡️' : '🍽️';
      console.log(`  ✅ ${kosherStatus} Added: ${dishData.name} (${dishData.slotCategory})`);
      added++;
    } catch (error) {
      console.error(`  ❌ Error adding ${dishData.name}:`, error);
      errors++;
    }
  }

  // Final summary
  const totalDishes = await prisma.dish.count();
  const kosherDishes = await prisma.dish.count({ where: { kosher: true } });
  const nonKosherDishes = totalDishes - kosherDishes;

  console.log('\n' + '='.repeat(60));
  console.log('📊 Import Summary:');
  console.log(`   Added: ${added}`);
  console.log(`   Skipped: ${skipped}`);
  console.log(`   Errors: ${errors}`);
  console.log('\n📊 Database Summary:');
  console.log(`   Total dishes: ${totalDishes}`);
  console.log(`   Kosher dishes: ${kosherDishes}`);
  console.log(`   Non-kosher dishes: ${nonKosherDishes}`);

  // Category breakdown
  const categories = ['main_chicken', 'main_beef', 'side_veg', 'side_starch', 'soup', 'muffin'];
  console.log('\n📋 Category Breakdown:');
  for (const cat of categories) {
    const count = await prisma.dish.count({ where: { slotCategory: cat } });
    const kosherCount = await prisma.dish.count({ where: { slotCategory: cat, kosher: true } });
    console.log(`   ${cat}: ${count} total (${kosherCount} kosher)`);
  }
}

addDishes()
  .catch((error) => {
    console.error('❌ Error:', error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
